# pip and Actions updates are automatic. Cargo's pinned Prime path dependencies
# live in the ignored prime-agent/ checkout, so Cargo Dependabot cannot fetch
# their manifests. rust-parity.yml builds and license-checks both actual graphs;
# Cargo update automation is an explicit open REPO-04 audit gate.
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
