# syntax=docker/dockerfile:1
# Generated by omega_prime.grokbot.deploy; regenerate instead of editing by hand.
# Build from the repository root: docker build -t omega-prime-mcp .

FROM python:3.12-slim-bookworm AS build
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
RUN python -m venv /opt/venv
COPY requirements-lock.txt /tmp/requirements-lock.txt
RUN /opt/venv/bin/pip install --no-cache-dir -r /tmp/requirements-lock.txt

FROM python:3.12-slim-bookworm AS runtime
LABEL org.opencontainers.image.title="omega-prime-mcp" \
      org.opencontainers.image.description="Omega Prime Grok Bot tool host (MCP over SSE)" \
      org.opencontainers.image.source="https://github.com/swcstudiospace/omes-bot" \
      org.opencontainers.image.licenses="AGPL-3.0-only"
RUN groupadd --system --gid 10001 omega-prime \
 && useradd --system --uid 10001 --gid 10001 --no-create-home \
      --home-dir /var/lib/omega-prime --shell /usr/sbin/nologin omega-prime \
 && install -d -o 10001 -g 10001 -m 0700 \
      /var/lib/omega-prime /var/lib/omega-prime/state /var/lib/omega-prime/audit
COPY --from=build /opt/venv /opt/venv
COPY --chmod=a+rX,go-w omega_prime /app/omega_prime
ENV PATH=/opt/venv/bin:$PATH \
    PYTHONPATH=/app \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    HOME=/var/lib/omega-prime \
    OMEGA_PRIME_STATE_DIR=/var/lib/omega-prime/state \
    OMEGA_PRIME_AUDIT_LOG=/var/lib/omega-prime/audit/audit.jsonl
WORKDIR /app
EXPOSE 8000
HEALTHCHECK --interval=15s --timeout=5s --start-period=20s --retries=3 \
  CMD ["python", "-c", "import sys, urllib.request; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=3).status == 200 else 1)"]
STOPSIGNAL SIGTERM
USER 10001:10001
ENTRYPOINT ["python", "-m", "omega_prime.mcp_server"]
CMD ["--root", "/app", "--transport", "sse", "--host", "0.0.0.0", "--port", "8000", "--token-file", "/run/secrets/omega_prime_token", "--audit-log", "/var/lib/omega-prime/audit/audit.jsonl", "--home", "/var/lib/omega-prime", "--shutdown-grace", "20", "--log-format", "json"]
