"""Behavior-parity fixtures for the Prime port (CONN-04).

Each JSON fixture under ``tests/parity/`` captures Prime behavior for one
slice of the ported surface, documented with its upstream source file. The
fixtures are generated by reading the Rust/Python sources (the Rust
baseline's role is the Phase 54 CI oracle); hermetic Python tests must not
require a Rust toolchain. This runner drives the ported implementation and
asserts the fixture's expectations.
"""

from __future__ import annotations

import json
import time
from pathlib import Path

import pytest

from omega_prime.agent.goals import STATUSES, goal_token_delta_for_usage
from omega_prime.agent.rlm import (
    ACTIVITY_KINDS,
    COLLECT_STATUSES,
    SUBAGENT_STATUSES,
    NoRlmHost,
    RlmHost,
)
from omega_prime.learning.harness import (
    KINDS,
    SCOPES,
    HarnessState,
    _validate_refinement_event,
)
from omega_prime.prime.autonomous import STOP_REASONS

PARITY_DIR = Path(__file__).parent / "parity"


def _fixture(name: str) -> dict:
    return json.loads((PARITY_DIR / name).read_text(encoding="utf-8"))


class _Parent:
    def __init__(self, tmp_path):
        self.delegate_depth = 0
        self.max_depth = 2
        self.max_children = 4
        self.session_dir = str(tmp_path)
        self.session_name = None


def test_no_host_error_strings():
    fixture = _fixture("rlm_no_host_errors.json")
    host = NoRlmHost()
    with pytest.raises(RuntimeError) as excinfo:
        host.spawn("x", name="y")
    assert str(excinfo.value) == fixture["spawn_error"]
    with pytest.raises(RuntimeError) as excinfo:
        host.create_session("x")
    assert str(excinfo.value) == fixture["create_session_error"]
    assert host.list_subagents() == []
    assert host.collect() == []
    for target in fixture["unknown_target_cases"]:
        expected = fixture["unknown_target_template"].format(target=target)
        with pytest.raises(ValueError) as delete_error:
            host.delete_subagent(target)
        assert str(delete_error.value) == expected
        with pytest.raises(ValueError) as collect_error:
            host.collect([target])
        assert str(collect_error.value) == expected


def test_progress_note_cap_and_throttle(tmp_path):
    fixture = _fixture("rlm_progress_note.json")
    for index, case in enumerate(fixture["cases"]):
        # A fresh host per case: the 10s throttle is per-child state.
        host = RlmHost(
            _Parent(tmp_path / f"case{index}"),
            run_child=lambda prompt, model=None, thinking=None: "ok",
        )
        handle = host.spawn("work", name="kid")
        message = case["message"] * case["repeat"]
        if "error" in case:
            with pytest.raises(ValueError, match=case["error"]):
                host.progress_note(handle.rlm_child_id, message)
        else:
            assert host.progress_note(handle.rlm_child_id, message).accepted is True
    host = RlmHost(
        _Parent(tmp_path / "throttle"),
        run_child=lambda prompt, model=None, thinking=None: "ok",
    )
    handle = host.spawn("work", name="kid")
    throttle = fixture["throttle"]
    assert (
        host.progress_note(handle.rlm_child_id, "first").accepted
        is throttle["first_accepted"]
    )
    second = host.progress_note(handle.rlm_child_id, "second")
    assert second.accepted is throttle["immediate_second_accepted"]
    assert second.retry_after_ms is not None
    assert 0 < second.retry_after_ms <= fixture["throttle_seconds"] * 1000


def test_collect_timeout_snapshot(tmp_path):
    fixture = _fixture("rlm_collect_timeout.json")

    def slow(prompt, model=None, thinking=None):
        time.sleep(2.0)
        return "late"

    host = RlmHost(_Parent(tmp_path), run_child=slow)
    host.spawn("slow work", name="kid")
    started = time.monotonic()
    results = host.collect(timeout_ms=fixture["timeout_ms"])
    assert time.monotonic() - started < 1.0
    assert len(results) == 1
    assert results[0].status in fixture["unsettled_statuses"]
    assert results[0].settled is fixture["settled"]


def test_goal_token_delta_cases():
    fixture = _fixture("goal_token_delta.json")
    for case in fixture["cases"]:
        assert goal_token_delta_for_usage(case["usage"]) == case["delta"], case


def test_harness_validation_rejections(tmp_path):
    fixture = _fixture("harness_validation.json")
    state = HarnessState(tmp_path)
    for case in fixture["entry_rejections"]:
        entry = case["entry"]
        with pytest.raises(ValueError, match=case["error"]):
            state.upsert(
                case["kind"],
                entry.get("id", ""),
                title=entry.get("title", ""),
                body=entry.get("body"),
                tags=entry.get("tags"),
            )
    for case in fixture["event_rejections"]:
        with pytest.raises(ValueError, match=case["error"]):
            _validate_refinement_event(case["event"])


def test_status_vocabularies_are_verbatim():
    fixture = _fixture("status_vocabularies.json")
    assert sorted(SUBAGENT_STATUSES) == sorted(fixture["subagent_statuses"])
    assert sorted(COLLECT_STATUSES) == sorted(fixture["collect_statuses"])
    assert sorted(ACTIVITY_KINDS) == sorted(fixture["activity_kinds"])
    assert sorted(STATUSES) == sorted(fixture["goal_statuses"])
    assert sorted(KINDS) == sorted(fixture["harness_kinds"])
    assert sorted(SCOPES) == sorted(fixture["harness_scopes"])
    assert sorted(STOP_REASONS) == sorted(fixture["autonomous_stop_reasons"])
