"""Generate the tool catalog from the roster + live registry schemas.

`python -m omes.tooling.catalog --out docs/tool-catalog.md` renders one
section per rostered tool in roster order, with family, description,
required parameters, and the approval flag. `--check` exits 1 when the
committed file differs from a fresh render, so CI fails on drift instead
of shipping stale docs. No network: the default registry builds locally.
"""

from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path
from typing import Any

from omes.mcp_server import default_registry, roster_names
from omes.tools.coding import CODING_TOOL_NAMES
from omes.tools.delegate import DELEG_TOOL_NAMES
from omes.tools.discord import DISCORD_TOOL_NAMES
from omes.tools.growth import GROWTH_TOOL_NAMES
from omes.tools.ide import IDE_TOOL_NAMES
from omes.tools.infra import INFRA_TOOL_NAMES
from omes.tools.lead import LEAD_TOOL_NAMES
from omes.tools.mobile import MOBILE_TOOL_NAMES
from omes.tools.packs import PACKS_TOOL_NAMES
from omes.tools.platform import PLATFORM_TOOL_NAMES
from omes.tools.quality import QUALITY_TOOL_NAMES
from omes.tools.substrate_tools import SUBSTRATE_TOOL_NAMES
from omes.tools.systems import SYS_TOOL_NAMES
from omes.tools.telegram import TELEGRAM_TOOL_NAMES
from omes.tools.ultrathink import ULT_TOOL_NAMES
from omes.tools.webpack import WEB_TOOL_NAMES
from omes.tools.x import X_TOOL_NAMES

FAMILIES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Coding", CODING_TOOL_NAMES),
    ("Growth", GROWTH_TOOL_NAMES),
    ("Delegate", DELEG_TOOL_NAMES),
    ("Platform", PLATFORM_TOOL_NAMES),
    ("IDE", IDE_TOOL_NAMES),
    ("X", X_TOOL_NAMES),
    ("Telegram", TELEGRAM_TOOL_NAMES),
    ("Discord", DISCORD_TOOL_NAMES),
    ("Lead", LEAD_TOOL_NAMES),
    ("Systems", SYS_TOOL_NAMES),
    ("Web", WEB_TOOL_NAMES),
    ("Mobile", MOBILE_TOOL_NAMES),
    ("Infra", INFRA_TOOL_NAMES),
    ("Quality", QUALITY_TOOL_NAMES),
    ("App packs", PACKS_TOOL_NAMES),
    ("Ultrathink", ULT_TOOL_NAMES),
    ("Substrate", SUBSTRATE_TOOL_NAMES),
)

HEADER = """# Tool catalog

DO NOT EDIT — generated by `python -m omes.tooling.catalog`.
Rebuild with `--out docs/tool-catalog.md`; CI fails when this file drifts.

"""


def render(root: str | Path, home: str | Path) -> str:
    """Render the catalog for the roster under ``root``."""
    root = Path(root)
    roster_path = root / "omes" / "contracts" / "tool-rosters" / "omes.yaml"
    roster = roster_names(roster_path.read_text(encoding="utf-8"))
    registry = default_registry(root, Path(home))
    schemas = {}
    for item in registry.schemas():
        fn = item.get("function", {})
        if isinstance(fn.get("name"), str):
            schemas[fn["name"]] = fn
    families = {}
    for family, names in FAMILIES:
        for name in names:
            families[name] = family
    lines = [HEADER.rstrip("\n"), ""]
    for name in roster:
        fn = schemas.get(name, {})
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- Family: {families.get(name, 'Unregistered')}")
        lines.append(f"- Approval: {'required' if registry.approval_required(name) else 'not required'}")
        required = (fn.get("parameters") or {}).get("required") or []
        lines.append(f"- Required params: {', '.join(required) if required else 'none'}")
        lines.append("")
        lines.append(fn.get("description", "Not served by the default registry."))
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Render or check the catalog. Exit 0 on success."""
    parser = argparse.ArgumentParser(prog="omes-tool-catalog")
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = (args.root or Path(__file__).resolve().parents[2]).resolve()
    out = args.out or (root / "docs" / "tool-catalog.md")
    with tempfile.TemporaryDirectory(prefix="omes-catalog-") as tmp:
        fresh = render(root, Path(tmp))
    if args.check:
        try:
            current = out.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"catalog --check: cannot read {out}: {exc}", file=sys.stderr)
            return 1
        if current != fresh:
            print(f"catalog --check: {out} is stale; rerun with --out", file=sys.stderr)
            return 1
        print(f"catalog --check: {out} up to date")
        return 0
    out.write_text(fresh, encoding="utf-8")
    print(f"catalog wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["FAMILIES", "main", "render"]
