"""Generate the tool catalog from the roster + live registry schemas.

`python -m omega_prime.tooling.catalog --out docs/tool-catalog.md` renders one
section per rostered tool in roster order, with family, description,
required parameters, and the approval flag. `--check` exits 1 when the
committed file differs from a fresh render, so CI fails on drift instead
of shipping stale docs. No network: the default registry builds locally.
"""

from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

from omega_prime.mcp_server import default_registry, roster_names
from omega_prime.tools.agent_message import MESSAGING_TOOL_NAMES
from omega_prime.tools.autonomous import AUTONOMOUS_TOOL_NAMES
from omega_prime.tools.coding import CODING_TOOL_NAMES
from omega_prime.tools.cron_admin import CRON_ADMIN_TOOL_NAMES
from omega_prime.tools.delegate import DELEG_TOOL_NAMES
from omega_prime.tools.discord import DISCORD_TOOL_NAMES
from omega_prime.tools.durable_surface import DURABLE_TOOL_NAMES
from omega_prime.tools.goals import GOAL_TOOL_NAMES
from omega_prime.tools.growth import GROWTH_TOOL_NAMES
from omega_prime.tools.harness import HARNESS_TOOL_NAMES
from omega_prime.tools.heartbeat import HEARTBEAT_TOOL_NAMES
from omega_prime.tools.ide import IDE_TOOL_NAMES
from omega_prime.tools.infra import INFRA_TOOL_NAMES
from omega_prime.tools.lead import LEAD_TOOL_NAMES
from omega_prime.tools.learning_surface import LEARNING_TOOL_NAMES
from omega_prime.tools.mobile import MOBILE_TOOL_NAMES
from omega_prime.tools.omega_command import OMEGA_COMMAND_TOOL_NAMES
from omega_prime.tools.packs import PACKS_TOOL_NAMES
from omega_prime.tools.platform import PLATFORM_TOOL_NAMES
from omega_prime.tools.prime_runtime import KERNEL_TOOL_NAMES
from omega_prime.tools.quality import QUALITY_TOOL_NAMES
from omega_prime.tools.rlm import RLM_TOOL_NAMES
from omega_prime.tools.substrate_tools import SUBSTRATE_TOOL_NAMES
from omega_prime.tools.systems import SYS_TOOL_NAMES
from omega_prime.tools.telegram import TELEGRAM_TOOL_NAMES
from omega_prime.tools.ultrathink import ULT_TOOL_NAMES
from omega_prime.tools.webpack import WEB_TOOL_NAMES
from omega_prime.tools.x import X_TOOL_NAMES

FAMILIES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Coding", CODING_TOOL_NAMES),
    ("Growth", GROWTH_TOOL_NAMES),
    ("Delegate", DELEG_TOOL_NAMES),
    ("Omega command", OMEGA_COMMAND_TOOL_NAMES),
    ("Platform", PLATFORM_TOOL_NAMES),
    ("IDE", IDE_TOOL_NAMES),
    ("X", X_TOOL_NAMES),
    ("Telegram", TELEGRAM_TOOL_NAMES),
    ("Discord", DISCORD_TOOL_NAMES),
    ("Lead", LEAD_TOOL_NAMES),
    ("Systems", SYS_TOOL_NAMES),
    ("Web", WEB_TOOL_NAMES),
    ("Mobile", MOBILE_TOOL_NAMES),
    ("Infra", INFRA_TOOL_NAMES),
    ("Quality", QUALITY_TOOL_NAMES),
    ("App packs", PACKS_TOOL_NAMES),
    ("Ultrathink", ULT_TOOL_NAMES),
    ("Substrate", SUBSTRATE_TOOL_NAMES),
    ("Cron", CRON_ADMIN_TOOL_NAMES),
    ("Learning", LEARNING_TOOL_NAMES),
    ("Durable", DURABLE_TOOL_NAMES),
    ("RLM", RLM_TOOL_NAMES),
    ("Harness", HARNESS_TOOL_NAMES),
    ("Goals", GOAL_TOOL_NAMES),
    ("Heartbeat", HEARTBEAT_TOOL_NAMES),
    ("Autonomous", AUTONOMOUS_TOOL_NAMES),
    ("Messaging", MESSAGING_TOOL_NAMES),
    ("Kernel", KERNEL_TOOL_NAMES),
)

HEADER = """# Tool catalog

DO NOT EDIT — generated by `python -m omega_prime.tooling.catalog`.
Rebuild with `--out docs/tool-catalog.md`; CI fails when this file drifts.

"""


def full_inventory_registry(root: Path, home: Path):
    """Registry with every rostered family registered for metadata reads.

    The default registry config-gates Prime families (default off) and skips
    live-parent families, so asking it for absent tools would invent
    default-false/empty metadata (WARN-03). The catalog instead registers the
    actual family definitions: real ``register_*`` calls against the real
    root, a throwaway session registry for messaging, an unbound RLM parent —
    and ``delegate_task`` comes from the default registry itself, which
    registers it on the in-process desk parent (DESK-03). Handlers are never
    dispatched here, so no capability operation executes during generation.
    """
    from omega_prime.agent.messaging import SessionRegistry
    from omega_prime.tools.agent_message import register_messaging_tools
    from omega_prime.tools.autonomous import register_autonomous_tools
    from omega_prime.tools.goals import register_goal_tools
    from omega_prime.tools.harness import register_harness_tools
    from omega_prime.tools.heartbeat import register_heartbeat_tools
    from omega_prime.tools.prime_runtime import register_prime_kernel_tools
    from omega_prime.tools.rlm import register_rlm_tools

    registry = default_registry(root, home)
    register_harness_tools(registry, root, enabled=True)
    register_goal_tools(registry, root, enabled=True)
    register_heartbeat_tools(registry, root, enabled=True)
    register_autonomous_tools(registry, root, enabled=True)
    register_messaging_tools(registry, "catalog", session_registry=SessionRegistry())
    register_rlm_tools(registry, None)
    register_prime_kernel_tools(registry, root)
    return registry


def render(root: str | Path, home: str | Path) -> str:
    """Render the catalog for the roster under ``root``."""
    root = Path(root)
    roster_path = (
        root / "omega_prime" / "contracts" / "tool-rosters" / "omega-prime.yaml"
    )
    roster = roster_names(roster_path.read_text(encoding="utf-8"))
    registry = full_inventory_registry(root, Path(home))
    schemas = {}
    for item in registry.schemas():
        fn = item.get("function", {})
        if isinstance(fn.get("name"), str):
            schemas[fn["name"]] = fn
    families = {}
    for family, names in FAMILIES:
        for name in names:
            families[name] = family
    lines = [HEADER.rstrip("\n"), ""]
    for name in roster:
        fn = schemas.get(name)
        if fn is None:
            raise SystemExit(
                f"tool catalog: roster names {name!r} with no registered "
                "definition; register its family before regenerating"
            )
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- Family: {families.get(name, 'Unregistered')}")
        lines.append(
            f"- Approval: {'required' if registry.approval_required(name) else 'not required'}"
        )
        required = (fn.get("parameters") or {}).get("required") or []
        lines.append(
            f"- Required params: {', '.join(required) if required else 'none'}"
        )
        lines.append("")
        lines.append(fn.get("description", ""))
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Render or check the catalog. Exit 0 on success."""
    parser = argparse.ArgumentParser(prog="omega-prime-tool-catalog")
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = (args.root or Path(__file__).resolve().parents[2]).resolve()
    out = args.out or (root / "docs" / "tool-catalog.md")
    with tempfile.TemporaryDirectory(prefix="omega-prime-catalog-") as tmp:
        fresh = render(root, Path(tmp))
    if args.check:
        try:
            current = out.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"catalog --check: cannot read {out}: {exc}", file=sys.stderr)
            return 1
        if current != fresh:
            print(f"catalog --check: {out} is stale; rerun with --out", file=sys.stderr)
            return 1
        print(f"catalog --check: {out} up to date")
        return 0
    out.write_text(fresh, encoding="utf-8")
    print(f"catalog wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = ["FAMILIES", "full_inventory_registry", "main", "render"]
