# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Spectrum Web Co
"""Deployment kit: render hardened artifacts for the Grok Bot tool host and check them.

`render` writes deterministic deployment artifacts for one of four targets
(`docker`, `compose`, `systemd`, `k8s`). Every target runs the host as a
non-root user on a read-only root filesystem with one writable state volume and
`/tmp`, reads its bearer token from a file the platform mounts (a secret is
never written into an artifact), and exposes `/healthz` and `/readyz` for the
platform's probes.

`check` scans rendered or hand-edited artifacts and reports findings with
stable ids (`FINDING_CATALOG`). It is text-based and stdlib-only: YAML files are
read with a small block-YAML subset reader, so no PyYAML is needed at runtime.

CLI: `python -m omega_prime.grokbot.deploy render|check ...`.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import re
import shlex
import sys
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NamedTuple

from omega_prime.grokbot._io import atomic_write_text

TARGETS = ("docker", "compose", "systemd", "k8s")

DEFAULT_NAME = "omega-prime-mcp"
DEFAULT_IMAGE = "ghcr.io/swcstudiospace/omega-prime-mcp:0.1.0"
DEFAULT_PORT = 8000
DEFAULT_UID = 10001

SOURCE_URL = "https://github.com/swcstudiospace/omes-bot"
DOCS_URL = f"{SOURCE_URL}/blob/main/docs/deploy.md"
BASE_IMAGE = "python:3.12-slim-bookworm"
LOCKFILE = "requirements-lock.txt"

TOKEN_FILE = "/run/secrets/omega_prime_token"
TOKEN_SECRET_NAME = "omega_prime_token"
STATE_ROOT = "/var/lib/omega-prime"
STATE_DIR = f"{STATE_ROOT}/state"
AUDIT_LOG = f"{STATE_ROOT}/audit/audit.jsonl"
APP_ROOT = "/app"
SHUTDOWN_GRACE = 20
STOP_GRACE = 30
PRESTOP_SECONDS = 5
TERMINATION_GRACE = 45

GENERATED_MARKER = "Generated by omega_prime.grokbot.deploy"
_GENERATED_NOTE = f"{GENERATED_MARKER}; regenerate instead of editing by hand."

# systemd layout (see docs/deploy.md)
SYSTEMD_ROOT = "/opt/omega-prime"
SYSTEMD_PYTHON = f"{SYSTEMD_ROOT}/venv/bin/python"
SYSTEMD_STATE = "%S/omega-prime"

# Every `check` finding id: (severity, what it means). Documented in docs/deploy.md.
FINDING_CATALOG: dict[str, tuple[str, str]] = {
    "run-as-root": ("error", "the workload runs as root or declares no non-root user"),
    "privileged": ("error", "the workload runs privileged"),
    "host-network": ("error", "the workload shares the host network namespace"),
    "host-pid": ("error", "the workload shares the host PID namespace"),
    "missing-healthcheck": (
        "error",
        "no container healthcheck (Dockerfile HEALTHCHECK, compose healthcheck)",
    ),
    "missing-probe": (
        "error",
        "a Kubernetes container lacks a liveness or readiness probe",
    ),
    "latest-tag": ("error", "an image reference is untagged or uses the `latest` tag"),
    "inline-secret": ("error", "a credential is written into the artifact"),
    "privilege-escalation": ("error", "privilege escalation is explicitly allowed"),
    "missing-no-new-privileges": (
        "error",
        "no-new-privileges is not enforced (compose, systemd) or "
        "allowPrivilegeEscalation is not false (Kubernetes)",
    ),
    "unparseable": ("error", "the file could not be read, so it could not be verified"),
    "writable-rootfs": ("warning", "the root filesystem is not read-only"),
    "missing-resource-limits": ("warning", "no memory limit is set"),
    "missing-network-policy": (
        "warning",
        "a Kubernetes workload is present without any NetworkPolicy",
    ),
    "unrecognized-file": (
        "warning",
        "an explicitly named file is not a Dockerfile, compose, Kubernetes or unit file",
    ),
    "promote-without-staging-evidence": (
        "warning",
        "production promotion has no staging receipt or image digest",
    ),
    "missing-promotion-approval-record": (
        "warning",
        "production promotion has no approval or audit record",
    ),
}

_NAME_RE = re.compile(r"^[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?$")
_COMPONENT = r"[a-z0-9]+(?:(?:[._]|__|-+)[a-z0-9]+)*"
_DOMAIN = r"[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?(?::[0-9]+)?"
_IMAGE_RE = re.compile(
    rf"^(?:{_DOMAIN}/)?{_COMPONENT}(?:/{_COMPONENT})*"
    r"(?::[A-Za-z0-9_][A-Za-z0-9_.-]{0,127})?"
    r"(?:@sha256:[a-f0-9]{64})?$"
)
_URL_RE = re.compile(r"^https?://[^\s\"'\\\x00-\x1f\x7f]+$")


class DeployError(ValueError):
    """A render input is invalid or an output file cannot be written safely."""


@dataclass(frozen=True)
class Finding:
    """One hardening finding. `id` is stable and documented."""

    id: str
    severity: str
    file: str
    message: str

    def to_dict(self) -> dict[str, str]:
        return {
            "id": self.id,
            "severity": self.severity,
            "file": self.file,
            "message": self.message,
        }


# --------------------------------------------------------------------------- render


def _validate(
    *, name: str, image: str, port: int, public_url: str | None, uid: int
) -> None:
    if not isinstance(name, str) or not _NAME_RE.match(name):
        raise DeployError(f"name {name!r} is not a DNS label (a-z, 0-9, '-', <= 63)")
    if not isinstance(image, str) or len(image) > 255 or not _IMAGE_RE.match(image):
        raise DeployError(f"image {image!r} is not a valid image reference")
    if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
        raise DeployError(f"port {port!r} must be an integer 1-65535")
    if isinstance(uid, bool) or not isinstance(uid, int) or uid < 1000:
        raise DeployError(f"uid {uid!r} must be an integer >= 1000")
    if public_url is not None and (
        not isinstance(public_url, str) or not _URL_RE.match(public_url)
    ):
        raise DeployError("public_url must be an http(s) URL without spaces or quotes")


def _server_args(
    *,
    root: str,
    host: str,
    port: int,
    token_file: str,
    audit_log: str,
    home: str,
    public_url: str | None,
) -> list[str]:
    args = [
        "--root",
        root,
        "--transport",
        "sse",
        "--host",
        host,
        "--port",
        str(port),
        "--token-file",
        token_file,
        "--audit-log",
        audit_log,
        "--home",
        home,
        "--shutdown-grace",
        str(SHUTDOWN_GRACE),
        "--log-format",
        "json",
    ]
    if public_url:
        args = [*args, "--public-url", public_url]
    return args


def _container_args(port: int, public_url: str | None) -> list[str]:
    return _server_args(
        root=APP_ROOT,
        host="0.0.0.0",
        port=port,
        token_file=TOKEN_FILE,
        audit_log=AUDIT_LOG,
        home=STATE_ROOT,
        public_url=public_url,
    )


def _health_code(port: int) -> str:
    """Stdlib-only liveness probe used by Docker and compose healthchecks."""
    return (
        "import sys, urllib.request; "
        f"sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:{port}/healthz', "
        "timeout=3).status == 200 else 1)"
    )


_ENTRYPOINT = ["python", "-m", "omega_prime.mcp_server"]


def _render_dockerfile(
    *, name: str, port: int, public_url: str | None, uid: int
) -> str:
    cmd = json.dumps(_container_args(port, public_url))
    health = json.dumps(["python", "-c", _health_code(port)])
    lines = [
        "# syntax=docker/dockerfile:1",
        f"# {_GENERATED_NOTE}",
        "# Build from the repository root: docker build -t omega-prime-mcp .",
        "",
        f"FROM {BASE_IMAGE} AS build",
        "ENV PIP_DISABLE_PIP_VERSION_CHECK=1",
        "RUN python -m venv /opt/venv",
        f"COPY {LOCKFILE} /tmp/{LOCKFILE}",
        f"RUN /opt/venv/bin/pip install --no-cache-dir -r /tmp/{LOCKFILE}",
        "",
        f"FROM {BASE_IMAGE} AS runtime",
        f'LABEL org.opencontainers.image.title="{name}" \\',
        '      org.opencontainers.image.description="Omega Prime Grok Bot tool host '
        '(MCP over SSE)" \\',
        f'      org.opencontainers.image.source="{SOURCE_URL}" \\',
        '      org.opencontainers.image.licenses="AGPL-3.0-only"',
        f"RUN groupadd --system --gid {uid} omega-prime \\",
        f" && useradd --system --uid {uid} --gid {uid} --no-create-home \\",
        f"      --home-dir {STATE_ROOT} --shell /usr/sbin/nologin omega-prime \\",
        f" && install -d -o {uid} -g {uid} -m 0700 \\",
        f"      {STATE_ROOT} {STATE_DIR} {STATE_ROOT}/audit",
        "COPY --from=build /opt/venv /opt/venv",
        f"COPY --chmod=a+rX,go-w omega_prime {APP_ROOT}/omega_prime",
        "ENV PATH=/opt/venv/bin:$PATH \\",
        f"    PYTHONPATH={APP_ROOT} \\",
        "    PYTHONUNBUFFERED=1 \\",
        "    PYTHONDONTWRITEBYTECODE=1 \\",
        f"    HOME={STATE_ROOT} \\",
        f"    OMEGA_PRIME_STATE_DIR={STATE_DIR} \\",
        f"    OMEGA_PRIME_AUDIT_LOG={AUDIT_LOG}",
        f"WORKDIR {APP_ROOT}",
        f"EXPOSE {port}",
        "HEALTHCHECK --interval=15s --timeout=5s --start-period=20s --retries=3 \\",
        f"  CMD {health}",
        "STOPSIGNAL SIGTERM",
        f"USER {uid}:{uid}",
        f"ENTRYPOINT {json.dumps(_ENTRYPOINT)}",
        f"CMD {cmd}",
    ]
    return "\n".join(lines) + "\n"


_DOCKERIGNORE = (
    ".git",
    ".github",
    ".venv",
    "venv",
    ".planning",
    "hermes-agent",
    "oh-my-pi",
    "prime-agent",
    "openhands*",
    "native",
    "kb",
    "assets",
    "docs",
    "omega_prime/tests",
    "**/__pycache__",
    "**/*.pyc",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "*.egg-info",
    "*.tgz",
    "**/*.db",
    "**/*.db-journal",
    "**/*.sqlite*",
    "**/.env",
    "**/.env.*",
    "**/secrets",
    "**/*.pem",
    "**/*.key",
    ".receipts",
    "omega_prime/memory/MEMORY.md",
    "omega_prime/memory/USER.md",
)


def _render_dockerignore() -> str:
    return "\n".join([f"# {_GENERATED_NOTE}", *_DOCKERIGNORE]) + "\n"


def _render_compose(
    *, name: str, image: str, port: int, public_url: str | None, uid: int
) -> str:
    service: dict[str, Any] = {
        "image": image,
        "command": _container_args(port, public_url),
        "user": f"{uid}:{uid}",
        "read_only": True,
        "tmpfs": ["/tmp"],
        "cap_drop": ["ALL"],
        "security_opt": ["no-new-privileges:true"],
        "ports": [f"127.0.0.1:{port}:{port}"],
        "secrets": [TOKEN_SECRET_NAME],
        "volumes": [f"{name}-state:{STATE_ROOT}"],
        "healthcheck": {
            "test": ["CMD", "python", "-c", _health_code(port)],
            "interval": "15s",
            "timeout": "5s",
            "retries": 3,
            "start_period": "20s",
        },
        "stop_signal": "SIGTERM",
        "stop_grace_period": f"{STOP_GRACE}s",
        "mem_limit": "1g",
        "pids_limit": 512,
        "restart": "unless-stopped",
    }
    doc: dict[str, Any] = {
        "name": name,
        "services": {name: service},
        "secrets": {TOKEN_SECRET_NAME: {"file": f"./secrets/{TOKEN_SECRET_NAME}"}},
        "volumes": {f"{name}-state": {}},
    }
    header = [
        f"# {_GENERATED_NOTE}",
        "# The token file is never inlined. Create it first (see docs/deploy.md):",
        f"#   install -d -m 0700 secrets && openssl rand -hex 24 > secrets/{TOKEN_SECRET_NAME}",
        f"#   chmod 600 secrets/{TOKEN_SECRET_NAME} && sudo chown {uid}:{uid} secrets/{TOKEN_SECRET_NAME}",
        "# The port is published on loopback only; put a TLS reverse proxy in front.",
    ]
    return "\n".join([*header, *_emit(doc)]) + "\n"


_TOKEN_COPY_CODE = (
    "import os; "
    "data = open('/run/token-src/omega_prime_token', 'rb').read(); "
    "fd = os.open('/run/secrets/omega_prime_token', "
    "os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600); "
    "os.write(fd, data); os.close(fd)"
)


def _render_k8s(
    *, name: str, image: str, port: int, public_url: str | None, uid: int
) -> str:
    labels = {"app.kubernetes.io/name": name}
    container_security = {
        "allowPrivilegeEscalation": False,
        "capabilities": {"drop": ["ALL"]},
        "readOnlyRootFilesystem": True,
        "runAsNonRoot": True,
        "runAsUser": uid,
        "seccompProfile": {"type": "RuntimeDefault"},
    }
    init_container = {
        "name": "token-init",
        "image": image,
        "command": ["python", "-c", _TOKEN_COPY_CODE],
        "securityContext": container_security,
        "resources": {
            "requests": {"cpu": "10m", "memory": "32Mi"},
            "limits": {"cpu": "100m", "memory": "64Mi"},
        },
        "volumeMounts": [
            {"name": "token-src", "mountPath": "/run/token-src", "readOnly": True},
            {"name": "token", "mountPath": "/run/secrets"},
        ],
    }
    container = {
        "name": name,
        "image": image,
        "args": _container_args(port, public_url),
        "ports": [{"name": "http", "containerPort": port, "protocol": "TCP"}],
        "securityContext": container_security,
        "livenessProbe": {
            "httpGet": {"path": "/healthz", "port": "http"},
            "periodSeconds": 10,
            "timeoutSeconds": 3,
            "failureThreshold": 3,
        },
        "readinessProbe": {
            "httpGet": {"path": "/readyz", "port": "http"},
            "periodSeconds": 5,
            "timeoutSeconds": 3,
            "failureThreshold": 2,
        },
        "startupProbe": {
            "httpGet": {"path": "/healthz", "port": "http"},
            "periodSeconds": 2,
            "failureThreshold": 30,
        },
        "lifecycle": {
            "preStop": {"exec": {"command": ["sleep", str(PRESTOP_SECONDS)]}}
        },
        "resources": {
            "requests": {"cpu": "100m", "memory": "256Mi"},
            "limits": {"cpu": "1", "memory": "1Gi"},
        },
        "volumeMounts": [
            {"name": "tmp", "mountPath": "/tmp"},
            {"name": "state", "mountPath": STATE_ROOT},
            {"name": "token", "mountPath": "/run/secrets", "readOnly": True},
        ],
    }
    pod_spec = {
        "automountServiceAccountToken": False,
        "terminationGracePeriodSeconds": TERMINATION_GRACE,
        "securityContext": {
            "fsGroup": uid,
            "runAsGroup": uid,
            "runAsNonRoot": True,
            "runAsUser": uid,
            "seccompProfile": {"type": "RuntimeDefault"},
        },
        "initContainers": [init_container],
        "containers": [container],
        "volumes": [
            {"name": "tmp", "emptyDir": {"sizeLimit": "64Mi"}},
            {"name": "state", "emptyDir": {"sizeLimit": "1Gi"}},
            {"name": "token", "emptyDir": {"medium": "Memory", "sizeLimit": "1Mi"}},
            {
                "name": "token-src",
                "secret": {
                    "secretName": "omega-prime-token",
                    "defaultMode": 288,
                    "items": [{"key": TOKEN_SECRET_NAME, "path": TOKEN_SECRET_NAME}],
                },
            },
        ],
    }
    deployment = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {"name": name, "labels": labels},
        "spec": {
            "replicas": 1,
            "revisionHistoryLimit": 3,
            "selector": {"matchLabels": labels},
            "strategy": {
                "type": "RollingUpdate",
                "rollingUpdate": {"maxSurge": 1, "maxUnavailable": 0},
            },
            "template": {"metadata": {"labels": labels}, "spec": pod_spec},
        },
    }
    service = {
        "apiVersion": "v1",
        "kind": "Service",
        "metadata": {"name": name, "labels": labels},
        "spec": {
            "type": "ClusterIP",
            "selector": labels,
            "ports": [
                {"name": "http", "port": port, "targetPort": "http", "protocol": "TCP"}
            ],
        },
    }
    network_policy = {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "NetworkPolicy",
        "metadata": {"name": name, "labels": labels},
        "spec": {
            "podSelector": {"matchLabels": labels},
            "policyTypes": ["Ingress"],
            "ingress": [
                {
                    "from": [
                        {
                            "podSelector": {
                                "matchLabels": {"omega-prime-mcp-client": "true"}
                            }
                        }
                    ],
                    "ports": [{"port": port, "protocol": "TCP"}],
                }
            ],
        },
    }
    pdb = {
        "apiVersion": "policy/v1",
        "kind": "PodDisruptionBudget",
        "metadata": {"name": name, "labels": labels},
        "spec": {"maxUnavailable": 1, "selector": {"matchLabels": labels}},
    }
    header = [
        f"# {_GENERATED_NOTE}",
        "# Create the token Secret first (see docs/deploy.md):",
        "#   kubectl create secret generic omega-prime-token "
        f"--from-file={TOKEN_SECRET_NAME}=./token",
        "# One replica: SSE and Streamable HTTP sessions live in the process, so scale",
        "# out only behind session affinity. The init container copies the token to a",
        "# 0600 file the host accepts (secret volumes gain group-read through fsGroup).",
    ]
    docs = ["\n".join(_emit(d)) for d in (deployment, service, network_policy, pdb)]
    return "\n".join(header) + "\n---\n" + "\n---\n".join(docs) + "\n"


def _sd_quote(arg: str) -> str:
    """Quote one ExecStart word. Callers escape `%` and `$` in user data first."""
    if arg and not re.search(r"[\s\"'\\;]", arg):
        return arg
    return '"' + arg.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_systemd(*, name: str, port: int, public_url: str | None, uid: int) -> str:
    del uid  # DynamicUser allocates the uid
    url = public_url.replace("%", "%%").replace("$", "$$") if public_url else None
    args = _server_args(
        root=SYSTEMD_ROOT,
        host="127.0.0.1",
        port=port,
        token_file="%d/" + TOKEN_SECRET_NAME,
        audit_log=f"{SYSTEMD_STATE}/audit/audit.jsonl",
        home=SYSTEMD_STATE,
        public_url=url,
    )
    exec_start = " ".join(
        _sd_quote(a) for a in [SYSTEMD_PYTHON, "-m", "omega_prime.mcp_server", *args]
    )
    env = [
        f"PYTHONPATH={SYSTEMD_ROOT}",
        "PYTHONUNBUFFERED=1",
        "PYTHONDONTWRITEBYTECODE=1",
        f"HOME={SYSTEMD_STATE}",
        f"OMEGA_PRIME_STATE_DIR={SYSTEMD_STATE}/state",
    ]
    lines = [
        f"# {_GENERATED_NOTE}",
        "# Install under /etc/systemd/system/ (see docs/deploy.md).",
        "[Unit]",
        f"Description=Omega Prime Grok Bot tool host ({name})",
        f"Documentation={DOCS_URL}",
        "After=network-online.target",
        "Wants=network-online.target",
        "",
        "[Service]",
        "Type=exec",
        f"ExecStart={exec_start}",
        "Environment=" + " ".join(f'"{item}"' for item in env),
        "DynamicUser=yes",
        "StateDirectory=omega-prime",
        "StateDirectoryMode=0700",
        f"LoadCredential={TOKEN_SECRET_NAME}:/etc/omega-prime/token",
        "UMask=0077",
        "NoNewPrivileges=yes",
        "ProtectSystem=strict",
        "ProtectHome=yes",
        "PrivateTmp=yes",
        "PrivateDevices=yes",
        "ProtectKernelTunables=yes",
        "ProtectKernelModules=yes",
        "ProtectKernelLogs=yes",
        "ProtectControlGroups=yes",
        "ProtectClock=yes",
        "ProtectHostname=yes",
        "RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX",
        "RestrictNamespaces=yes",
        "RestrictRealtime=yes",
        "RestrictSUIDSGID=yes",
        "LockPersonality=yes",
        "CapabilityBoundingSet=",
        "AmbientCapabilities=",
        "SystemCallArchitectures=native",
        "SystemCallFilter=@system-service",
        "SystemCallErrorNumber=EPERM",
        "KillSignal=SIGTERM",
        f"TimeoutStopSec={STOP_GRACE}",
        "Restart=on-failure",
        "RestartSec=2",
        "MemoryMax=1G",
        "TasksMax=512",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
    ]
    return "\n".join(lines) + "\n"


# --- YAML emitter (deterministic block style; strings are always JSON-quoted)

_PLAIN_KEY = re.compile(r"^[A-Za-z_][A-Za-z0-9_./-]*$")
_FLOW_LIMIT = 76


def _scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    raise TypeError(f"cannot emit {type(value).__name__}")


def _key(key: str) -> str:
    return key if _PLAIN_KEY.match(key) else json.dumps(key)


def _is_scalar(value: Any) -> bool:
    return value is None or isinstance(value, (bool, int, str))


def _emit(value: Any, indent: int = 0) -> list[str]:
    pad = " " * indent
    lines: list[str] = []
    if isinstance(value, dict):
        for key, item in value.items():
            head = f"{pad}{_key(key)}:"
            if _is_scalar(item):
                lines.append(f"{head} {_scalar(item)}")
            elif isinstance(item, dict):
                lines.extend(
                    [f"{head} {{}}"] if not item else [head, *_emit(item, indent + 2)]
                )
            elif not item:
                lines.append(f"{head} []")
            elif all(_is_scalar(x) for x in item):
                flow = "[" + ", ".join(_scalar(x) for x in item) + "]"
                if len(head) + 1 + len(flow) <= _FLOW_LIMIT:
                    lines.append(f"{head} {flow}")
                else:
                    lines.extend([head, *_emit(item, indent + 2)])
            else:
                lines.extend([head, *_emit(item, indent + 2)])
        return lines
    for item in value:
        if _is_scalar(item):
            lines.append(f"{pad}- {_scalar(item)}")
            continue
        inner = _emit(item, indent + 2)
        lines.append(f"{pad}- {inner[0].lstrip()}")
        lines.extend(inner[1:])
    return lines


def _is_generated(path: Path) -> bool:
    try:
        with path.open(encoding="utf-8") as handle:
            head = [handle.readline() for _ in range(4)]
    except (OSError, UnicodeDecodeError):
        return False
    return any(GENERATED_MARKER in line for line in head)


def render(
    target: str,
    out_dir: str | Path,
    *,
    name: str = DEFAULT_NAME,
    image: str = DEFAULT_IMAGE,
    port: int = DEFAULT_PORT,
    public_url: str | None = None,
    uid: int = DEFAULT_UID,
    overwrite: bool = False,
) -> list[Path]:
    """Write the artifacts of `target` into `out_dir` and return their paths.

    Output is deterministic: the same arguments always produce the same bytes. A
    file this function did not generate is never replaced unless `overwrite`.
    """
    if target not in TARGETS:
        raise DeployError(
            f"unknown target {target!r}; choose from {', '.join(TARGETS)}"
        )
    _validate(name=name, image=image, port=port, public_url=public_url, uid=uid)
    files: dict[str, str]
    if target == "docker":
        files = {
            "Dockerfile": _render_dockerfile(
                name=name, port=port, public_url=public_url, uid=uid
            ),
            ".dockerignore": _render_dockerignore(),
        }
    elif target == "compose":
        files = {
            "compose.yaml": _render_compose(
                name=name, image=image, port=port, public_url=public_url, uid=uid
            )
        }
    elif target == "systemd":
        files = {
            f"{name}.service": _render_systemd(
                name=name, port=port, public_url=public_url, uid=uid
            )
        }
    else:
        files = {
            f"{name}.yaml": _render_k8s(
                name=name, image=image, port=port, public_url=public_url, uid=uid
            )
        }
    out = Path(out_dir)
    if out.exists() and not out.is_dir():
        raise DeployError(f"{out} exists and is not a directory")
    paths = [out / filename for filename in files]
    if not overwrite:
        for path in paths:
            if path.exists() and not (path.is_file() and _is_generated(path)):
                raise DeployError(
                    f"{path} exists and was not generated by this tool; "
                    "use --force to replace it"
                )
    out.mkdir(parents=True, exist_ok=True)
    for path, text in zip(paths, files.values(), strict=True):
        atomic_write_text(path, text, mode=0o644)
    return paths


# --------------------------------------------------------------------------- YAML subset reader


class _YamlError(ValueError):
    pass


class _Line(NamedTuple):
    indent: int
    text: str  # comment-stripped, right-trimmed
    raw: str
    blank: bool


def _strip_comment(text: str) -> str:
    quote = ""
    i = 0
    while i < len(text):
        ch = text[i]
        if quote:
            if quote == '"' and ch == "\\":
                i += 2
                continue
            if ch == quote:
                quote = ""
        elif ch in "\"'" and (i == 0 or text[i - 1] in " \t[{,:-"):
            quote = ch
        elif ch == "#" and (i == 0 or text[i - 1] in " \t"):
            return text[:i].rstrip()
        i += 1
    return text.rstrip()


def _prepare_lines(raw_lines: list[str]) -> list[_Line]:
    out: list[_Line] = []
    for raw in raw_lines:
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            out.append(_Line(0, "", raw, True))
            continue
        body = raw.lstrip(" ")
        if body.startswith("\t"):
            raise _YamlError("tab indentation is not supported")
        text = _strip_comment(body)
        out.append(_Line(len(raw) - len(body), text, raw, not text))
    return out


def _quoted_end(text: str, start: int) -> int:
    quote = text[start]
    i = start + 1
    while i < len(text):
        ch = text[i]
        if quote == '"' and ch == "\\":
            i += 2
            continue
        if ch == quote:
            if quote == "'" and text[i + 1 : i + 2] == "'":
                i += 2
                continue
            return i
        i += 1
    raise _YamlError("unterminated quoted string")


def _unquote(token: str) -> str:
    if token[0] == '"':
        try:
            value = json.loads(token)
        except ValueError:
            return token[1:-1]
        return str(value)
    return token[1:-1].replace("''", "'")


_INT_RE = re.compile(r"^-?\d+$")


def _plain(token: str) -> Any:
    if token in ("", "~", "null", "Null", "NULL"):
        return None
    if token in ("true", "True", "TRUE"):
        return True
    if token in ("false", "False", "FALSE"):
        return False
    if _INT_RE.match(token):
        return int(token)
    return token


def _flow(text: str, pos: int, *, in_map_key: bool = False) -> tuple[Any, int]:
    while pos < len(text) and text[pos] == " ":
        pos += 1
    if pos >= len(text):
        raise _YamlError("unexpected end of flow collection")
    ch = text[pos]
    if ch == "[":
        items: list[Any] = []
        pos += 1
        while True:
            while pos < len(text) and text[pos] == " ":
                pos += 1
            if pos >= len(text):
                raise _YamlError("unterminated flow list")
            if text[pos] == "]":
                return items, pos + 1
            value, pos = _flow(text, pos)
            items.append(value)
            while pos < len(text) and text[pos] == " ":
                pos += 1
            if pos < len(text) and text[pos] == ",":
                pos += 1
            elif pos >= len(text) or text[pos] != "]":
                raise _YamlError("bad flow list")
    if ch == "{":
        result: dict[str, Any] = {}
        pos += 1
        while True:
            while pos < len(text) and text[pos] == " ":
                pos += 1
            if pos >= len(text):
                raise _YamlError("unterminated flow map")
            if text[pos] == "}":
                return result, pos + 1
            key, pos = _flow(text, pos, in_map_key=True)
            while pos < len(text) and text[pos] == " ":
                pos += 1
            if pos >= len(text) or text[pos] != ":":
                raise _YamlError("bad flow map")
            value, pos = _flow(text, pos + 1)
            result[str(key)] = value
            while pos < len(text) and text[pos] == " ":
                pos += 1
            if pos < len(text) and text[pos] == ",":
                pos += 1
            elif pos >= len(text) or text[pos] != "}":
                raise _YamlError("bad flow map")
    if ch in ('"', "'"):
        end = _quoted_end(text, pos)
        return _unquote(text[pos : end + 1]), end + 1
    stops = ",]}:" if in_map_key else ",]}"
    end = pos
    while end < len(text) and text[end] not in stops:
        end += 1
    return _plain(text[pos:end].strip()), end


def _scalar_from_text(text: str) -> Any:
    text = text.strip()
    if text[:1] in ("&", "*", "!") or text.startswith("<<"):
        raise _YamlError("anchors, aliases and tags are not supported")
    if text[:1] in ("[", "{"):
        value, pos = _flow(text, 0)
        if text[pos:].strip():
            raise _YamlError("trailing text after flow collection")
        return value
    if text[:1] in ('"', "'"):
        end = _quoted_end(text, 0)
        if text[end + 1 :].strip():
            raise _YamlError("trailing text after quoted string")
        return _unquote(text[: end + 1])
    return _plain(text)


def _split_key(text: str) -> tuple[str, str] | None:
    """Split `key: rest`; None when `text` is not a mapping entry."""
    if text[:1] in ("[", "{"):
        return None
    if text[:1] in ('"', "'"):
        end = _quoted_end(text, 0)
        after = text[end + 1 :]
        if after.startswith(":") and (len(after) == 1 or after[1] == " "):
            return _unquote(text[: end + 1]), after[1:].strip()
        return None
    if text.endswith(":"):
        return text[:-1].rstrip(), ""
    idx = text.find(": ")
    if idx < 0:
        return None
    return text[:idx].rstrip(), text[idx + 2 :].strip()


def _is_item(text: str) -> bool:
    return text == "-" or text.startswith("- ")


_BLOCK_MARKERS = {"|", "|-", "|+", ">", ">-", ">+"}


class _Reader:
    def __init__(self, lines: list[_Line]) -> None:
        self.lines = lines
        self.i = 0

    def peek(self) -> _Line | None:
        while self.i < len(self.lines) and self.lines[self.i].blank:
            self.i += 1
        return self.lines[self.i] if self.i < len(self.lines) else None

    def node(self, indent: int) -> Any:
        line = self.peek()
        if line is None or line.indent < indent:
            return None
        if _is_item(line.text):
            return self.items(line.indent)
        return self.mapping(line.indent)

    def items(self, indent: int) -> list[Any]:
        result: list[Any] = []
        while True:
            line = self.peek()
            if line is None or line.indent != indent or not _is_item(line.text):
                return result
            rest = line.text[1:].lstrip(" ")
            if not rest:
                self.i += 1
                nxt = self.peek()
                result.append(
                    self.node(nxt.indent) if nxt and nxt.indent > indent else None
                )
                continue
            offset = len(line.text) - len(rest)
            self.lines[self.i] = line._replace(indent=indent + offset, text=rest)
            if _is_item(rest):
                result.append(self.items(indent + offset))
            elif _split_key(rest) is not None:
                result.append(self.mapping(indent + offset))
            else:
                self.i += 1
                result.append(_scalar_from_text(rest))

    def block_scalar(self, indent: int) -> str:
        collected: list[str] = []
        base: int | None = None
        while self.i < len(self.lines):
            line = self.lines[self.i]
            if line.blank:
                collected.append("")
                self.i += 1
                continue
            if line.indent <= indent:
                break
            base = line.indent if base is None else min(base, line.indent)
            collected.append(line.raw.rstrip("\n"))
            self.i += 1
        width = base or 0
        return "\n".join(x[width:] if x else "" for x in collected).rstrip("\n") + "\n"

    def mapping(self, indent: int) -> dict[str, Any]:
        result: dict[str, Any] = {}
        while True:
            line = self.peek()
            if line is None or line.indent < indent:
                return result
            if line.indent > indent:
                raise _YamlError(f"unexpected indentation: {line.text!r}")
            if _is_item(line.text):
                return result
            split = _split_key(line.text)
            if split is None:
                raise _YamlError(f"expected 'key: value', got {line.text!r}")
            key, rest = split
            if key == "<<":
                raise _YamlError("merge keys are not supported")
            if key in result:
                raise _YamlError(f"duplicate key {key!r}")
            self.i += 1
            value: Any
            if not rest:
                nxt = self.peek()
                if nxt is not None and nxt.indent > indent:
                    value = self.node(nxt.indent)
                elif nxt is not None and nxt.indent == indent and _is_item(nxt.text):
                    value = self.items(indent)
                else:
                    value = None
            elif rest in _BLOCK_MARKERS:
                value = self.block_scalar(indent)
            else:
                value = _scalar_from_text(rest)
            result[key] = value


def _load_yaml(text: str) -> list[Any]:
    """Parse a multi-document block-YAML subset. Raises `_YamlError` otherwise."""
    documents: list[list[str]] = [[]]
    for raw in text.splitlines():
        if raw.rstrip() == "---" or raw.startswith("--- "):
            documents.append([])
            continue
        if raw.rstrip() == "...":
            continue
        documents[-1].append(raw)
    result: list[Any] = []
    for raw_lines in documents:
        reader = _Reader(_prepare_lines(raw_lines))
        first = reader.peek()
        if first is None:
            continue
        value = reader.node(first.indent)
        if reader.peek() is not None:
            raise _YamlError("could not read the whole document")
        result.append(value)
    return result


# --------------------------------------------------------------------------- check

_SECRET_SUFFIXES = (
    "token",
    "secret",
    "password",
    "passwd",
    "apikey",
    "api_key",
    "api-key",
    "private_key",
    "access_key",
    "secret_key",
    "_key",
)
_FALSEY = {"true", "false", "null", "none", "yes", "no", "on", "off", "~", ""}
_TOKEN_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "a GitHub token",
        re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_\w{20,})"),
    ),
    ("a GitLab token", re.compile(r"\bglpat-[A-Za-z0-9_-]{16,}")),
    ("an API key", re.compile(r"\bsk-[A-Za-z0-9_-]{20,}")),
    ("a Slack token", re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}")),
    ("an AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("a JWT", re.compile(r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]+")),
    ("a private key", re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----")),
    (
        "a hex secret",
        re.compile(r"(?<![A-Za-z0-9:@/_.-])[0-9a-fA-F]{32,}(?![A-Za-z0-9])"),
    ),
)


def _secret_key(key: str) -> bool:
    return key.lower().endswith(_SECRET_SUFFIXES)


def _literal_value(value: Any) -> bool:
    """True when `value` is a concrete value rather than a reference or a flag."""
    if value is None or isinstance(value, bool):
        return False
    text = str(value).strip()
    if text.lower() in _FALSEY or _INT_RE.match(text):
        return False
    return not text.startswith(("$", "%", "/", "file:", "<", "secret:"))


class _Report:
    def __init__(self, file: str) -> None:
        self.file = file
        self.findings: list[Finding] = []
        self._seen: set[tuple[str, str]] = set()

    def add(self, finding_id: str, message: str) -> None:
        if (finding_id, message) in self._seen:
            return
        self._seen.add((finding_id, message))
        self.findings.append(
            Finding(finding_id, FINDING_CATALOG[finding_id][0], self.file, message)
        )

    def secret_env(self, where: str, key: str, value: Any) -> None:
        if _secret_key(key) and _literal_value(value):
            self.add("inline-secret", f"{where}: {key} is set to a literal value")

    def secret_args(self, where: str, tokens: Sequence[str]) -> None:
        for index, token in enumerate(tokens):
            if token.startswith("--token=") or (
                token == "--token"
                and index + 1 < len(tokens)
                and _literal_value(tokens[index + 1])
            ):
                self.add("inline-secret", f"{where}: --token carries a literal value")

    def scan_text(self, text: str) -> None:
        for line in text.splitlines():
            code = line.strip()
            if not code or code.startswith("#"):
                continue
            for kind, pattern in _TOKEN_PATTERNS:
                if pattern.search(code):
                    self.add(
                        "inline-secret", f"the file contains what looks like {kind}"
                    )


def _words(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(x) for x in value]
    if isinstance(value, str):
        try:
            return shlex.split(value)
        except ValueError:
            return value.split()
    return []


def _image_findings(report: _Report, where: str, ref: str) -> None:
    if "$" in ref or ref == "scratch" or "@sha256:" in ref:
        return
    last = ref.rsplit("/", 1)[-1]
    tag = last.split(":", 1)[1] if ":" in last else ""
    if not tag or tag == "latest":
        report.add("latest-tag", f"{where}: image {ref!r} is untagged or `latest`")


# --- Dockerfile


def _docker_instructions(text: str) -> list[tuple[str, str]]:
    result: list[tuple[str, str]] = []
    buffer = ""
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("#") or (not stripped and not buffer):
            continue
        if stripped.endswith("\\"):
            buffer += stripped[:-1] + " "
            continue
        full = (buffer + stripped).strip()
        buffer = ""
        if full:
            keyword, _, args = full.partition(" ")
            result.append((keyword.upper(), args.strip()))
    if buffer.strip():
        keyword, _, args = buffer.strip().partition(" ")
        result.append((keyword.upper(), args.strip()))
    return result


def _exec_words(args: str) -> list[str]:
    if args.startswith("["):
        try:
            parsed = json.loads(args)
        except ValueError:
            return []
        return [str(x) for x in parsed] if isinstance(parsed, list) else []
    return _words(args)


def _check_docker(text: str, report: _Report) -> None:
    stages: list[dict[str, Any]] = []
    aliases: dict[str, dict[str, Any]] = {}
    for keyword, args in _docker_instructions(text):
        if keyword == "FROM":
            parts = [p for p in args.split() if not p.startswith("--")]
            if not parts:
                continue
            ref = parts[0]
            stage: dict[str, Any] = {"user": None, "health": False, "ref": ref}
            parent = aliases.get(ref.lower())
            if parent is not None:
                stage["user"], stage["health"] = parent["user"], parent["health"]
            else:
                _image_findings(report, "FROM", ref)
            if len(parts) >= 3 and parts[1].upper() == "AS":
                aliases[parts[2].lower()] = stage
            stages.append(stage)
            continue
        if not stages:
            continue
        stage = stages[-1]
        if keyword == "USER":
            stage["user"] = args.split()[0] if args.split() else None
        elif keyword == "HEALTHCHECK":
            stage["health"] = not args.upper().startswith("NONE")
        elif keyword in ("ENV", "ARG"):
            try:
                tokens = shlex.split(args)
            except ValueError:
                tokens = args.split()
            if keyword == "ENV" and tokens and "=" not in tokens[0]:
                report.secret_env(keyword, tokens[0], " ".join(tokens[1:]))
            else:
                for token in tokens:
                    key, sep, value = token.partition("=")
                    if sep:
                        report.secret_env(keyword, key, value)
        elif keyword in ("CMD", "ENTRYPOINT"):
            report.secret_args(keyword, _exec_words(args))
    if not stages:
        report.add("unparseable", "no FROM instruction found")
        return
    final = stages[-1]
    user = final["user"]
    if user is None:
        report.add("run-as-root", "no USER instruction in the final stage")
    elif user.split(":")[0] in ("root", "0"):
        report.add("run-as-root", f"the final stage runs as USER {user}")
    if not final["health"]:
        report.add("missing-healthcheck", "the final stage has no HEALTHCHECK")


# --- systemd


def _unit_entries(text: str) -> list[tuple[str, str, str]]:
    entries: list[tuple[str, str, str]] = []
    section = ""
    pending = ""
    for raw in text.splitlines():
        line = raw.strip()
        if pending:
            line = pending + " " + line
            pending = ""
        if not line or line[0] in "#;":
            continue
        if line.endswith("\\"):
            pending = line[:-1].rstrip()
            continue
        if line.startswith("[") and line.endswith("]"):
            section = line[1:-1]
            continue
        key, sep, value = line.partition("=")
        if sep:
            entries.append((section, key.strip(), value.strip()))
    return entries


def _truthy(value: str) -> bool:
    return value.strip().lower() in ("yes", "true", "1", "on")


def _check_systemd(text: str, report: _Report) -> None:
    service = [(k, v) for s, k, v in _unit_entries(text) if s == "Service"]
    last = dict(service)
    user = last.get("User", "")
    if user in ("root", "0") or (not user and not _truthy(last.get("DynamicUser", ""))):
        report.add(
            "run-as-root", "the unit sets no non-root User= and no DynamicUser=yes"
        )
    if not _truthy(last.get("NoNewPrivileges", "")):
        report.add("missing-no-new-privileges", "NoNewPrivileges=yes is not set")
    if last.get("ProtectSystem", "").lower() not in ("strict", "full", "yes", "true"):
        report.add(
            "writable-rootfs", "ProtectSystem is not strict, so / stays writable"
        )
    if not any(k in last for k in ("MemoryMax", "MemoryLimit")):
        report.add("missing-resource-limits", "no MemoryMax= is set")
    for key, value in service:
        if key == "ExecStart":
            words = _words(value.lstrip("@-+!:"))
            report.secret_args("ExecStart", words)
        elif key == "Environment":
            for item in _words(value):
                name, sep, val = item.partition("=")
                if sep:
                    report.secret_env("Environment", name, val)
        elif key == "SetCredential":
            name, _, val = value.partition(":")
            if val:
                report.add(
                    "inline-secret", f"SetCredential= writes {name} into the unit"
                )


# --- compose and Kubernetes


def _env_pairs(env: Any) -> Iterator[tuple[str, Any]]:
    if isinstance(env, dict):
        yield from ((str(k), v) for k, v in env.items())
    elif isinstance(env, list):
        for item in env:
            if isinstance(item, str):
                key, sep, value = item.partition("=")
                if sep:
                    yield key, value


def _compose_user_root(user: Any) -> bool:
    if user is None or user == "":
        return True
    return str(user).split(":")[0] in ("root", "0")


def _has_no_new_privileges(options: Any) -> bool:
    if not isinstance(options, list):
        return False
    for option in options:
        text = str(option).replace("=", ":").lower()
        if text in ("no-new-privileges", "no-new-privileges:true"):
            return True
    return False


def _check_compose(doc: dict[str, Any], report: _Report) -> None:
    services = doc.get("services")
    if not isinstance(services, dict):
        return
    for sname, svc in services.items():
        if not isinstance(svc, dict):
            continue
        where = f"service {sname}"
        image = svc.get("image")
        if isinstance(image, str):
            _image_findings(report, where, image)
        elif "build" not in svc:
            report.add("latest-tag", f"{where}: no image reference")
        if _compose_user_root(svc.get("user")):
            report.add("run-as-root", f"{where}: no non-root `user:` is set")
        if svc.get("privileged") is True:
            report.add("privileged", f"{where}: privileged: true")
        if str(svc.get("network_mode", "")).lower() == "host":
            report.add("host-network", f"{where}: network_mode: host")
        if str(svc.get("pid", "")).lower() == "host":
            report.add("host-pid", f"{where}: pid: host")
        health = svc.get("healthcheck")
        test = health.get("test") if isinstance(health, dict) else None
        disabled = isinstance(health, dict) and (
            health.get("disable") is True or test == ["NONE"] or test == "NONE"
        )
        if not test or disabled:
            report.add("missing-healthcheck", f"{where}: no healthcheck is defined")
        if not _has_no_new_privileges(svc.get("security_opt")):
            report.add(
                "missing-no-new-privileges",
                f"{where}: security_opt lacks no-new-privileges:true",
            )
        if svc.get("read_only") is not True:
            report.add("writable-rootfs", f"{where}: read_only: true is not set")
        deploy = svc.get("deploy")
        limits = (
            deploy.get("resources", {}).get("limits")
            if isinstance(deploy, dict) and isinstance(deploy.get("resources"), dict)
            else None
        )
        if not (
            svc.get("mem_limit") or svc.get("memory") or (limits and "memory" in limits)
        ):
            report.add("missing-resource-limits", f"{where}: no memory limit is set")
        for key, value in _env_pairs(svc.get("environment")):
            report.secret_env(where, key, value)
        report.secret_args(where, _words(svc.get("command")))
        report.secret_args(where, _words(svc.get("entrypoint")))


_WORKLOADS = ("Deployment", "StatefulSet", "DaemonSet", "ReplicaSet", "Job", "Pod")


def _pod_spec(doc: dict[str, Any]) -> dict[str, Any] | None:
    kind = doc.get("kind")
    spec = doc.get("spec")
    if not isinstance(spec, dict):
        return None
    if kind == "Pod":
        return spec
    if kind in _WORKLOADS:
        template = spec.get("template")
        node = template.get("spec") if isinstance(template, dict) else None
        return node if isinstance(node, dict) else None
    if kind == "CronJob":
        job = spec.get("jobTemplate")
        job_spec = job.get("spec") if isinstance(job, dict) else None
        template = job_spec.get("template") if isinstance(job_spec, dict) else None
        node = template.get("spec") if isinstance(template, dict) else None
        return node if isinstance(node, dict) else None
    return None


def _k8s_container(
    report: _Report,
    where: str,
    container: dict[str, Any],
    pod_security: dict[str, Any],
    *,
    probes: bool,
) -> None:
    sec = container.get("securityContext")
    sec = sec if isinstance(sec, dict) else {}

    def effective(key: str) -> Any:
        return sec.get(key, pod_security.get(key))

    image = container.get("image")
    if isinstance(image, str):
        _image_findings(report, where, image)
    else:
        report.add("latest-tag", f"{where}: no image reference")
    run_user = effective("runAsUser")
    non_root = effective("runAsNonRoot") is True or (
        isinstance(run_user, int) and not isinstance(run_user, bool) and run_user > 0
    )
    if run_user == 0 or effective("runAsNonRoot") is False or not non_root:
        report.add("run-as-root", f"{where}: not forced to a non-root user")
    if sec.get("privileged") is True:
        report.add("privileged", f"{where}: privileged: true")
    escalation = sec.get("allowPrivilegeEscalation")
    if escalation is True:
        report.add("privilege-escalation", f"{where}: allowPrivilegeEscalation: true")
    elif escalation is not False:
        report.add(
            "missing-no-new-privileges",
            f"{where}: allowPrivilegeEscalation is not set to false",
        )
    if sec.get("readOnlyRootFilesystem") is not True:
        report.add("writable-rootfs", f"{where}: readOnlyRootFilesystem is not true")
    resources = container.get("resources")
    limits = resources.get("limits") if isinstance(resources, dict) else None
    if not (isinstance(limits, dict) and "memory" in limits):
        report.add("missing-resource-limits", f"{where}: no memory limit is set")
    if probes:
        missing = [
            key
            for key in ("livenessProbe", "readinessProbe")
            if not isinstance(container.get(key), dict)
        ]
        if missing:
            report.add("missing-probe", f"{where}: missing {', '.join(missing)}")
    env = container.get("env")
    if isinstance(env, list):
        for item in env:
            if isinstance(item, dict) and "valueFrom" not in item and "name" in item:
                report.secret_env(where, str(item["name"]), item.get("value"))
    report.secret_args(where, _words(container.get("args")))
    report.secret_args(where, _words(container.get("command")))


def _check_k8s_doc(doc: dict[str, Any], report: _Report) -> None:
    kind = doc.get("kind")
    meta = doc.get("metadata")
    label = f"{kind} {meta.get('name', '?')}" if isinstance(meta, dict) else str(kind)
    if kind == "Secret":
        for field in ("data", "stringData"):
            if doc.get(field):
                report.add(
                    "inline-secret", f"{label}: {field} holds inline secret values"
                )
        return
    spec = _pod_spec(doc)
    if spec is None:
        return
    if spec.get("hostNetwork") is True:
        report.add("host-network", f"{label}: hostNetwork: true")
    if spec.get("hostPID") is True:
        report.add("host-pid", f"{label}: hostPID: true")
    pod_security = spec.get("securityContext")
    pod_security = pod_security if isinstance(pod_security, dict) else {}
    for field, probes in (("containers", True), ("initContainers", False)):
        entries = spec.get(field)
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if isinstance(entry, dict):
                where = f"{label} {field[:-1]} {entry.get('name', '?')}"
                _k8s_container(report, where, entry, pod_security, probes=probes)


# --- driver

_DOCKER_NAMES = re.compile(r"^(?:Dockerfile(?:\..+)?|.+\.Dockerfile)$")
_SUFFIXES = (".yaml", ".yml", ".service")


def _candidate(path: Path) -> bool:
    return bool(_DOCKER_NAMES.match(path.name)) or path.suffix in _SUFFIXES


def _kind_of(path: Path, text: str) -> str | None:
    if path.suffix not in (".yaml", ".yml", ".service") and (
        _DOCKER_NAMES.match(path.name) or re.search(r"(?m)^FROM\s+\S", text)
    ):
        return "docker"
    if re.search(r"(?m)^\[Service\]\s*$", text):
        return "systemd"
    if path.suffix in (".yaml", ".yml"):
        return "yaml"
    return None


def _analyze(
    path: Path, label: str, *, explicit: bool
) -> tuple[list[Finding], list[dict[str, Any]], bool]:
    """Findings for one file, its k8s documents, and whether it is a workload file."""
    report = _Report(label)
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        report.add("unparseable", f"cannot read the file: {exc}")
        return report.findings, [], False
    kind = _kind_of(path, text)
    k8s_docs: list[dict[str, Any]] = []
    workload = False
    if kind == "docker":
        _check_docker(text, report)
    elif kind == "systemd":
        _check_systemd(text, report)
    elif kind == "yaml":
        try:
            docs = _load_yaml(text)
        except _YamlError as exc:
            report.add("unparseable", f"cannot read this YAML: {exc}")
            return report.findings, [], False
        recognized = False
        for doc in docs:
            if not isinstance(doc, dict):
                continue
            if isinstance(doc.get("services"), dict):
                recognized = True
                _check_compose(doc, report)
            elif "kind" in doc and "apiVersion" in doc:
                recognized = True
                _check_k8s_doc(doc, report)
                k8s_docs.append(doc)
                workload = workload or _pod_spec(doc) is not None
        if not recognized and explicit:
            report.add("unrecognized-file", "no compose services or Kubernetes objects")
    elif explicit:
        report.add(
            "unrecognized-file", "not a Dockerfile, compose, Kubernetes or unit file"
        )
    if kind is not None:
        report.scan_text(text)
    return report.findings, k8s_docs, workload


def _is_promotion_name(name: str) -> bool:
    """True when a file name marks the set as a production promotion."""
    base = name.lower()
    return base.startswith("promot") or base.startswith(("prod-", "prod_", "prod."))


def _is_staging_evidence(name: str) -> bool:
    """True for a staging receipt or an image digest file."""
    base = name.lower()
    return "staging" in base or base.endswith(".digest")


def _is_approval_record(name: str) -> bool:
    """True for a promotion approval or audit record file."""
    base = name.lower()
    return "approv" in base or "audit" in base


def _promotion_findings(peers: list[tuple[Path, str]]) -> list[Finding]:
    """Staging-first gate: a promotion marker without evidence warns, never errors."""
    promotion: str | None = None
    staging = False
    approval = False
    for file_path, label in peers:
        name = file_path.name
        if promotion is None and _is_promotion_name(name):
            promotion = label
        if _is_staging_evidence(name):
            staging = True
        if _is_approval_record(name):
            approval = True
    if promotion is None:
        return []
    findings: list[Finding] = []
    if not staging:
        findings.append(
            Finding(
                "promote-without-staging-evidence",
                "warning",
                promotion,
                "production promotion has no staging receipt or image digest; "
                "verify on staging first",
            )
        )
    if not approval:
        findings.append(
            Finding(
                "missing-promotion-approval-record",
                "warning",
                promotion,
                "production promotion has no approval or audit record",
            )
        )
    return findings


def check(path: str | Path) -> list[Finding]:
    """Scan a file or a directory of artifacts. Raises `FileNotFoundError` for a bad path."""
    root = Path(path)
    if not root.exists():
        raise FileNotFoundError(f"no such file or directory: {root}")
    findings: list[Finding] = []
    if root.is_dir():
        targets = [
            (p, p.relative_to(root).as_posix())
            for p in sorted(root.rglob("*"))
            if p.is_file() and _candidate(p)
        ]
        explicit = False
    else:
        targets = [(root, root.name)]
        explicit = True
    policies = 0
    first_workload: str | None = None
    for file_path, label in targets:
        file_findings, docs, workload = _analyze(file_path, label, explicit=explicit)
        findings.extend(file_findings)
        policies += sum(1 for d in docs if d.get("kind") == "NetworkPolicy")
        if workload and first_workload is None:
            first_workload = label
    if first_workload is not None and policies == 0:
        findings.append(
            Finding(
                "missing-network-policy",
                "warning",
                first_workload,
                "no NetworkPolicy restricts ingress to the workload",
            )
        )
    if root.is_dir():
        peers = [
            (p, p.relative_to(root).as_posix())
            for p in sorted(root.rglob("*"))
            if p.is_file()
        ]
    else:
        peers = [(root, root.name)]
        with contextlib.suppress(OSError):
            peers += [
                (p, p.name)
                for p in sorted(root.parent.iterdir())
                if p.is_file() and p != root
            ]
    findings.extend(_promotion_findings(peers))
    return sorted(
        findings, key=lambda f: (f.file, f.severity != "error", f.id, f.message)
    )


# --------------------------------------------------------------------------- CLI


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m omega_prime.grokbot.deploy",
        description="Render and check hardened deployment artifacts.",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    render_cmd = sub.add_parser("render", help="write the artifacts of one target")
    render_cmd.add_argument("--target", required=True, choices=TARGETS)
    render_cmd.add_argument("--out", required=True, type=Path, metavar="DIR")
    render_cmd.add_argument("--name", default=DEFAULT_NAME)
    render_cmd.add_argument("--image", default=DEFAULT_IMAGE)
    render_cmd.add_argument("--port", type=int, default=DEFAULT_PORT)
    render_cmd.add_argument("--public-url", default=None, metavar="URL")
    render_cmd.add_argument("--uid", type=int, default=DEFAULT_UID)
    render_cmd.add_argument(
        "--force", action="store_true", help="replace files this tool did not generate"
    )
    check_cmd = sub.add_parser("check", help="scan artifacts for hardening findings")
    check_cmd.add_argument("path", type=Path)
    check_cmd.add_argument(
        "--json", action="store_true", help="machine-readable output"
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry. Exit 0 clean or warnings only, 1 on an error finding, 2 on bad usage."""
    parser = _build_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        return exc.code if isinstance(exc.code, int) else 2
    if args.command == "render":
        try:
            paths = render(
                args.target,
                args.out,
                name=args.name,
                image=args.image,
                port=args.port,
                public_url=args.public_url,
                uid=args.uid,
                overwrite=args.force,
            )
        except (DeployError, OSError) as exc:
            print(f"deploy: {exc}", file=sys.stderr)
            return 2
        for path in paths:
            print(path)
        return 0
    try:
        findings = check(args.path)
    except OSError as exc:
        print(f"deploy: {exc}", file=sys.stderr)
        return 2
    errors = sum(1 for f in findings if f.severity == "error")
    if args.json:
        payload = {
            "ok": errors == 0,
            "errors": errors,
            "warnings": len(findings) - errors,
            "findings": [f.to_dict() for f in findings],
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        for f in findings:
            print(f"{f.file}: {f.severity} [{f.id}] {f.message}")
        print(f"{errors} error(s), {len(findings) - errors} warning(s)")
    return 1 if errors else 0


__all__ = [
    "DEFAULT_IMAGE",
    "DEFAULT_NAME",
    "DEFAULT_PORT",
    "DEFAULT_UID",
    "FINDING_CATALOG",
    "TARGETS",
    "DeployError",
    "Finding",
    "check",
    "main",
    "render",
]

if __name__ == "__main__":
    raise SystemExit(main())
